receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

processors:
  resourcedetection:
    detectors: [env, gcp]
    timeout: 2s
    override: false

exporters:
  googlecloud:
  googlemanagedprometheus:

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  telemetry:
    logs:
      level: "warn"
      encoding: json
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection]
      exporters: [googlecloud]
    metrics:
      receivers: [otlp]
      processors: [resourcedetection]
      exporters: [googlemanagedprometheus]
